
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: php:8.2-fpm  # Use PHP 8.2
        container_name: laravel_app
        restart: always
        working_dir: /var/www
        volumes:
            - .:/var/www
        depends_on:
            - mysql
        networks:
            - laravel_network

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        restart: always
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel_network

    mysql:
        image: mysql:8
        container_name: laravel_mysql
        restart: always
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel_user
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: rootpassword
        ports:
            - "8101:3306"
        networks:
            - laravel_network
        volumes:
            - ./tmp/mysql_data:/var/lib/mysql

volumes:
    mysql_data:

networks:
    laravel_network:
